#!/bin/bash

set -x

CC=gcc
CFLAGS="-Wall -Wextra -fsanitize=undefined,address -I./vendor/include"
LFLAGS="-lGL -lglfw -lm"
SRCS="canvas.c ./vendor/src/glad.c "

$CC $CFLAGS  -o canvas $SRCS $LFLAGS

if [ $? -eq 0 ]
then
    printf "\nBuild Successfully.\n"
    ./canvas
else
    exit 1
fi
